### ISSUE TITLE
[CI/CD] 배포 관련 파일 추가

### ISSUE THREAD

**Issue by cjh-19** [KW-MUJI/BE#112]
## 📝 Issue Description

CI/CD 배포를 위한 파일 추가 (https 적용 전)

## ✔️ To-do

- [x] 프로젝트 루트에 appspec.yml 추기
- [x] 프로젝트 루트에 deploy.sh 추가
- [x] 프로젝트 루트에 Dockerfile 추가
- [x] 블루, 그린 배포를 위해 프로젝트 루트에 docker-compose.blue.yml, docker-compose.green.yml 추가
- [x] EC2에 nginx.conf 파일 수정
