### ISSUE TITLE
[FIX] 오류 수정

### ISSUE THREAD

**Issue by pipi-shortstocking** [KW-MUJI/BE#144]
## 📝 Issue Description

프론트 측에서 전달받은 오류 수정

## ✔️ To-do

- [x] 비밀번호 재설정 시, 토큰 삭제
- [x] 팀플 세부 정보에서 start 값 전달
- [x] 마이페이지 메인 합치기
