### ISSUE TITLE
[FIX] LocalDateTime 시간 고정 및 null 입력 수정

### ISSUE THREAD

**Issue by cjh-19** [KW-MUJI/BE#152]
## 📝 Issue Description

캘린더 기능에서 LocalDateTime을 yyyy-MM-dd HH:mm:ss 로 고정
또한 개인 일정 추가 시, null 값 입력하도록 수정

## ✔️ To-do

- [x] LocalDateTime을 yyyy-MM-dd HH:mm:ss 로 고정
- [x] 개인 일정 추가 시, null 값 입력 가능
- [x] mysql에서 UserEventLinkEntity의 projectId null 허용
