### ISSUE TITLE
[FIX] My 팀플

### ISSUE THREAD

**Issue by pipi-shortstocking** [KW-MUJI/BE#173]
## 📝 Issue Description

/myteam/participation | GET, /myteam/applicant | GET

## ✔️ To-do

- [x] /myteam/participation | GET - CREATOR 넣기
- [x] /myteam/applicant | GET - 팀플 시작해도, 지원자 목록은 전부다 뜨는 걸로 수정
- [x] 팀플 시작하면 isOnGoing이 false
