### ISSUE TITLE
[FEAT] 설문조사 상태 컬럼 추가에 대한 변경 기능 추가 

### ISSUE THREAD

**Issue by cjh-19** [KW-MUJI/BE#31]
## 📝 Issue Description

survey 테이블에 isOngoing이라는 설문 상태(진행중, 종료) 컬럼을 추가함에 따른 기능 추가 및 dto 수정

## ✔️ To-do

- [x] /survey api에 대한 요청에 isOngoing 정보 추가
- [x] /survey/{surveyId} api에 대한 요청에 isOngoing 추가
- [x] /survey/create/{userId} api로 설문조사 생성에서 isOngoing 정보 추가
