### ISSUE TITLE
[FIX/FEAT] 캘린 변경사항에 맞게 수정

### ISSUE THREAD

**Issue by cjh-19** [KW-MUJI/BE#86]
## 📝 Issue Description

- 제목은 project 테이블의 name 컬럼
- 상세 내용은 usercalendar 테이블의 title 컬럼
- 캘린더 일정 삭제 기능(대학 일정 제외, usercalendar 일정만)

## ✔️ To-do

- [x] 팀플 일정의 제목은 project 테이블의 name 컬럼 반환
- [x] 팀플 일정의 상세 내용은 usercalendar 테이블의 title 컬럼 반환
- [x] usercalendar 일정 삭제 기능 추가
